name: Daily Prediction Pipeline

on:
  schedule:
    - cron: '30 3 * * *'  # Every day at 9:00 AM IST (03:30 UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log workflow start time
        run: |
          echo "🔁 Workflow triggered at:"
          echo "🕒 UTC  : $(date -u)"
          echo "🕒 IST  : $(TZ='Asia/Kolkata' date)"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          EMAIL_SENDER: kkhushi2707@gmail.com
          EMAIL_PASSWORD: czuk xdql ojuc mcll
          EMAIL_RECEIVER: kkhushi2707@gmail.com
        run: python script.py
